### ISSUE TITLE
Additional example

### ISSUE THREAD

**Issue by Alkohost** [flatironinstitute/mountainsort_examples#19]
Can you please add a step-by-step example with instructions for own data (jupyter example)?

According to issue #18  set a path to mountainsort4_1_0 using
sys.path.append('.../mountainsort_examples-master/python')
Is this step necessary or there are other ways to fix it?

According to .mda format descriptions generate for own data
raw.mda (easy to do with mdaio for Matlab)
geom.csv
params.json

To solve 'widjets' problem use
conda install -c tjd2002 'mountainlab_pytools=0.7.4'

All other initialization instructions according to ms4_jupyter_example.ipynb
and just call ms4_sort_dataset
 
What '.prv' is actually, when it necessary and when is not?

**Comment by tjd2002** [comment]
The files ending *_true are the original ‘ground truth’ data used to simulate spiking in the synthetic datasets.

When you are working with real electrophysiological recordings, you will not have these files, since you don’t know what the ground truth is (if you did, you wouldn’t need to do spike sorting 😁)

A .prv file is essentially a link to a larger data file elsewhere in the MountainLab search path. A .prv file can be used anywhere that the original file was used (I.e. you can generally just ignore this suffix).

**Comment by Alkohost** [comment]
Thank you, I understood all items and just asked for a more detailed ReadMe if possible. Please see the updated comment above.
