### ISSUE TITLE
Questions on the parameter settings

### ISSUE THREAD

**Issue by ukky17** [flatironinstitute/mountainsort_examples#9]
1. How should I set `adjacency_radius` parameter in `mountainsort4_1_0.sort_dataset` function?
I am using a linear probe (Neuronexus "A1x32-5mm-25-177"), tetrode (Neuronexus "A4x2-tet-5mm-150-200-121") and polytrode (Neuronexus "A1x32-Poly3-5mm-25s-177").

2. In my recording setting, channel # 8 is devoted for recording the external TTL pulse, not for recording the signals from the silicon probe. In that case, how should I set the coordinate of that channel in the geom.csv file?

**Comment by magland** [comment]
For the first question, the units of the adjacency_radius correspond to units in the geom.csv. Set the radius so that the neighborhoods have around 7 channels. Neighborhoods are defined as the ball of the given radius around the central channel of the neighborhood.

For number 2, currently there is no way to exclude channels in the sorting. One thing you might try is to set the channel to all zeros. That might work. Otherwise, you need to extract out a subset of the array as well as a subset of the geom file.
